for fig = findobj('Type','figure')'
   if isempty(fig.Name)
      continue;
   end
   savefig(fig, ['fig/fig/' fig.Name '.fig']);
   matlab2tikz(['fig/tikz/' fig.Name '.tex'], ...
      'figurehandle', fig, ...
      'parseStrings', false, ...
      ...'width', [floor(num2str(fig.Position(3))) 'pt'], ...
      ...'height', [floor(num2str(fig.Position(4))) 'pt'], ...
      'height', '\plotheight', ...
      'extraTikzpictureOptions', 'font=\small', ...
      'showInfo', false);
end

!\cp -rf fig/ ~/Arbeit/Oberseminar/